### ISSUE TITLE
CPB_calculation

### ISSUE THREAD

**Issue by smsaladi** [lauringlab/CodonShuffle#3]
I can't seem to locate the code to calculate codon pair bias that's referenced in `README.md`. Would you be able to help with this?

> Codon pair bias, calculated with custom R script CPB_calculation(n3, dN23, dN31, OR dN231)

**Comment by danielmjorge** [comment]
Hi,
Sorry the delay to answer. The code for codon pair bias calculation is located after line 1889 (tag: cpb) in the python file: codonShuffle.py . If you have any other question, let me know.
Thanks for using the script.
